### ISSUE TITLE
Meta: Security

### ISSUE THREAD

**Issue by mitra42** [mitra42/frugal-iot-server#9]
Issues relating to security on the server. 

- [ ] Should be on https rather than http
- [ ] Controls on who can access - via login to server
- [ ] Controls on who can access mqtt via userid/password (of user, not project)
